import { CONSULTATION_URL, CONTACT_EMAIL } from "../constants/tools.ts";

export function aboutSection(): string {
  return [
    "## About FocusReactive",
    "",
    "[FocusReactive](https://focusreactive.com) is a Next.js and headless-CMS migration agency. We move "
      + "enterprise sites off legacy monoliths and visual builders — Webflow, Framer, WordPress, AEM — onto "
      + "Sanity, Payload CMS, Storyblok and MedusaJS, and we do it without losing traffic, rankings or a "
      + "publishing day.",
    "",
    "- **Verified partners** of Sanity, Payload and Storyblok — we build on the platforms' own recommended "
      + "patterns, not around them.",
    "- **Our own [CMS Kit](https://github.com/focusreactive/cms-kit)** — the block and schema toolkit behind "
      + "roughly 40% faster delivery on projects shaped like this one.",
    "- **SEO and performance held as a requirement,** not a phase: redirect parity, metadata parity, 100/100 "
      + "Lighthouse, zero-downtime cutover.",
    "- **Open tooling.** The assessment you are reading was generated by a pipeline we publish, from the public "
      + "version of your site alone.",
    "",
    `👉 **[Get a free migration consultation](${CONSULTATION_URL})** or write to ${CONTACT_EMAIL} — send this `
      + "report along and we can go through the risks above line by line.",
  ].join("\n");
}
