export const DISCOVERY_STEP_PREFIX = "discovery";

export const DISCOVERY_SECTIONS_SCHEMA_STEP_ID = `${DISCOVERY_STEP_PREFIX}:sections:schema` as const;
export const DISCOVERY_SECTIONS_SUBJECT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:sections:subject` as const;
export const DISCOVERY_SECTIONS_JUDGE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:sections:judge` as const;
export const DISCOVERY_SECTIONS_ACCEPT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:sections:accept` as const;

export const DISCOVERY_SECTIONS_STEP_IDS = [
  DISCOVERY_SECTIONS_SCHEMA_STEP_ID,
  DISCOVERY_SECTIONS_SUBJECT_STEP_ID,
  DISCOVERY_SECTIONS_JUDGE_STEP_ID,
  DISCOVERY_SECTIONS_ACCEPT_STEP_ID,
] as const;

export const DISCOVERY_DEDUP_SCHEMA_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:schema` as const;
export const DISCOVERY_DEDUP_SUBJECT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:subject` as const;
export const DISCOVERY_DEDUP_JUDGE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:judge` as const;
export const DISCOVERY_DEDUP_ACCEPT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:accept` as const;

export const DISCOVERY_DEDUP_STEP_IDS = [
  DISCOVERY_DEDUP_SCHEMA_STEP_ID,
  DISCOVERY_DEDUP_SUBJECT_STEP_ID,
  DISCOVERY_DEDUP_JUDGE_STEP_ID,
  DISCOVERY_DEDUP_ACCEPT_STEP_ID,
] as const;

export const DISCOVERY_FINALIZE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:finalize` as const;

export const DISCOVERY_STEP_IDS = [
  ...DISCOVERY_SECTIONS_STEP_IDS,
  ...DISCOVERY_DEDUP_STEP_IDS,
  DISCOVERY_FINALIZE_STEP_ID,
] as const;
