// Transcribed from docs/design/report.design.html:698-723 (the agency close and the
// page footer).
import { CONSULTATION_URL, CONTACT_EMAIL } from "#report/constants/tools.ts";

import type { RenderContext } from "../render-context.ts";
import { FR_WORDMARK_LARGE_SVG } from "../constants/svg.ts";
import { escapeAttr, escapeHtml } from "../utils/escape.ts";
import { formatReportDate } from "../utils/format-date.ts";

export function closeSection(ctx: RenderContext): string {
  const generatedAt = escapeHtml(formatReportDate(ctx.input.generatedAt));
  const hostname = escapeHtml(new URL(ctx.input.sourceUrl).hostname);

  return `
  <div id="talk" style="border-top: 1px solid #171717; padding: 104px 0 88px;">
    <div class="wrap">
      <div style="display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 72px; align-items: start;">
        <div>
          ${FR_WORDMARK_LARGE_SVG}
          <h2 class="sec" style="margin-top: 32px; font-size: 40px;">Go through the risks<br />line by line with us</h2>
          <p class="body" style="margin-top: 20px; max-width: 46ch;"><a href="https://focusreactive.com">FocusReactive</a> is a Next.js and headless-CMS migration agency. We move enterprise sites off legacy monoliths and visual builders &mdash; Webflow, Framer, WordPress, AEM &mdash; onto Sanity, Payload CMS, Storyblok and MedusaJS, and we do it without losing traffic, rankings or a publishing day.</p>
          <div style="display: flex; gap: 12px; margin-top: 36px; flex-wrap: wrap;">
            <a href="${escapeAttr(CONSULTATION_URL)}" class="btn">Get a free migration consultation</a>
            <a href="mailto:${escapeAttr(CONTACT_EMAIL)}" class="btn-ghost">${escapeHtml(CONTACT_EMAIL)}</a>
          </div>
        </div>
        <div style="display: flex; flex-direction: column; gap: 1px; background: #1e1e1e; border: 1px solid #1e1e1e; border-radius: 16px; overflow: hidden;">
          <div style="background: #0a0a0a; padding: 24px 26px;"><h3 class="sub" style="font-size: 15px;">Verified partners of Sanity, Payload and Storyblok</h3><p class="body" style="font-size: 13px; margin-top: 8px;">We build on the platforms&rsquo; own recommended patterns, not around them.</p></div>
          <div style="background: #0a0a0a; padding: 24px 26px;"><h3 class="sub" style="font-size: 15px;">Our own CMS Kit</h3><p class="body" style="font-size: 13px; margin-top: 8px;">The block and schema toolkit behind roughly 40% faster delivery on projects shaped like this one.</p></div>
          <div style="background: #0a0a0a; padding: 24px 26px;"><h3 class="sub" style="font-size: 15px;">SEO and performance held as a requirement</h3><p class="body" style="font-size: 13px; margin-top: 8px;">Redirect parity, metadata parity, 100/100 Lighthouse, zero-downtime cutover.</p></div>
          <div style="background: #0a0a0a; padding: 24px 26px;"><h3 class="sub" style="font-size: 15px;">Open tooling</h3><p class="body" style="font-size: 13px; margin-top: 8px;">This assessment was generated by a pipeline we publish, from the public version of your site alone.</p></div>
        </div>
      </div>

      <div style="display: flex; align-items: center; justify-content: space-between; margin-top: 72px; padding-top: 28px; border-top: 1px solid #171717; font-size: 12.5px; color: #3d3d3d;">
        <span>Generated by the FocusReactive migration assessment pipeline &middot; ${generatedAt}</span>
        <span class="mono">${hostname}</span>
      </div>
    </div>
  </div>`;
}
